apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app.kubernetes.io/name: seankins
    name: seankins
  spec:
    output:
      to:
        kind: DockerImage
        name: seankins:latest
    source:
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile